// BOOKS ---------------------------------------
const SELECT_ALL_MOVIES = "SELECT_ALL_MOVIES";
const SELECT_MOVIE_BY_ID = "SELECT_MOVIE_BY_ID";
const UPDATE_MOVIE = "UPDATE_MOVIE";
const DELETE_MOVIE = "DELETE_MOVIE";
const INSERT_MOVIE = "INSERT_MOVIE";
const INSERT_GENRE_MOVIE = "INSERT_GENRE_MOVIE";
const EXIST_MOVIE = "EXIST_MOVIE";

// USER ---------------------------------------
const SELECT_ALL_USERS = "SELECT_ALL_USERS";
const SELECT_USER_BY_ID = "SELECT_USER_BY_ID";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";
const INSERT_USER = "INSERT_USER";
const REGISTER_USER = "REGISTER_USER";
const EXIST_USER = "EXIST_USER";
const LOGIN_USER = "LOGIN_USER";
const ADDFAV_USER = "ADDFAV_USER"
const DELETEFAV_USER = "DELETEFAV_USER";


module.exports = {
    SELECT_ALL_USERS,
    SELECT_USER_BY_ID,
    UPDATE_USER,
    DELETE_USER,
    INSERT_USER,
    REGISTER_USER,
    EXIST_USER,
    LOGIN_USER,
    ADDFAV_USER,
    DELETEFAV_USER,
    SELECT_ALL_MOVIES,
    SELECT_MOVIE_BY_ID,
    UPDATE_MOVIE,
    DELETE_MOVIE,
    INSERT_MOVIE,
    EXIST_MOVIE,
    INSERT_GENRE_MOVIE
}